baseURL = "https://rayancrasta.github.io/website/"
languageCode = 'en-us'
title = 'Rayan Crasta'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hey!'
homeIntroContent = """
I am a Software Engineer with a deep interest in backend engineering and software development.
I am interested in a range of topics, including algorithms, distributed systems, and databases. 

I write blogs and build projects on the topics that interest me; this is the place where you can find them.
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rayan-crasta/"

[[params.social]]
name = "medium"
url = "https://medium.com/@rayancr"

[[params.social]]
name = "github"
url = "https://github.com/rayancrasta"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "about"
url = "/about"

# Blog entries
[[params.blog]]
title = "Building a tweet ingestion and search backend like Twitter "
description = "Built a scalable tweet ingestion and search backend using Go, Kafka, and Elasticsearch, handling real-time data and safe content filtering."
url = "https://medium.com/@rayancr/building-a-tweet-ingestion-and-search-backend-like-twitter-using-go-kafka-and-elasticsearch-608b32e68252"
date = "2024-05-20"

[[params.blog]]
title = "Building a booking service backend like Ticketmaster / BookMyShow "
description = "Built a robust booking service backend like Ticketmaster using Go, Redis, and PostgreSQL, optimized for high traffic and real-time seat reservation"
url = "https://medium.com/@rayancr/building-a-booking-service-backend-like-ticketmaster-and-bookmyshow-using-go-redis-and-postgresql-a4caa1f1105e"
date = "2024-05-20"

[[params.blog]]
title = "Building a tweet ingestion and search backend like Twitter "
description = "Built a scalable tweet ingestion and search backend using Go, Kafka, and Elasticsearch, handling real-time data and safe content filtering."
url = "https://medium.com/@rayancr/building-a-tweet-ingestion-and-search-backend-like-twitter-using-go-kafka-and-elasticsearch-608b32e68252"
date = "2024-05-20"

[[params.blog]]
title = "Building a Realtime Collaborative Whiteboard"
description = "rchitecture and implementation of a real-time collaborative whiteboard using NodeJS, MongoDB, Nginx, and Redis, featuring seamless drawing updates and robust system consistency."
url = "https://medium.com/@rayancr/realtime-collaborative-whiteboard-using-nodejs-mongodb-nginx-lb-and-redis-a0f1d29a1462"
date = "2024-04-20"

[[params.blog]]
title = "SSH certificates in Linux — Step by Step Guide"
description = "SSH certificate-based authentication in Linux with this step-by-step guide, enhancing security and simplifying management"
url = "https://medium.com/@rayancr/ssh-certificates-in-linux-step-by-step-guide-36fe61097ed2"
date = "2023-05-20"

[[params.blog]]
title = "SSH certificate authentication — Better than keys?"
description = "Explore SSH certificates as an advanced alternative to traditional key-based authentication, offering enhanced security and flexibility"
url = "https://medium.com/@rayancr/ssh-certificate-authentication-better-than-keys-4261b2a17125"
date = "2023-04-16"

[[params.blog]]
title = "SFTP Setup using Password and Key based 2FA Authentication"
description = "Set up SFTP with 2FA by integrating password and key-based authentication on CentOS, enhancing security for file transfers"
url = "https://medium.com/@rayancr/sftp-setup-using-password-and-key-based-2fa-authentication-7caf11899299"
date = "2022-06-01"

[[params.blog]]
title = "Linux SSH Key + Password Auth for Users Stored in Active Directory"
description = "Enhancing SSH security on Linux with a 2FA setup using key and password authentication integrated with Active Directory."
url = "https://medium.com/@rayancr/linux-ssh-key-password-auth-for-users-stored-in-active-directory-949765e4c774"
date = "2022-06-12"

#projects
# Projects entries
[[params.projects]]
title = "MyShowSeat"
description = "Prototype of a booking service like major cinema and event booking sites like Ticketmaster and BookMyShow."
url = "https://github.com/rayancrasta/MyShowSeat"

# Projects entries
[[params.projects]]
title = "TweetOps"
description = "Twitter-like ingestion backend prototype using Go, FastAPI, Kafka, PostgreSQL and Elasticsearch with a profanity checker that flags tweets as safe or unsafe that help during searches."
url = "https://github.com/rayancrasta/TweetOps"

[[params.projects]]
title = "Tensorflow lite Meme classifier"
description = "Android app that classifies whether the image is a Meme or Not a Meme using Tensorflow Lite. (Prototype for a major project which classifies explicit images in realtime and quarantines it)"
url = "https://github.com/rayancrasta/TweetOphttps://github.com/rayancrasta/Meme-vs-Non-Meme-Android-App-Using-TFlite"




# Syntax highlight on code blocks
[markup]
  [markup.highlight]
    style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

relativeURLs = true